* "Injection" tests
+ Pick beaming angle (e.g. 15 deg) and some efficiency
+ For those work out expected number of detections
+ Plug this back in and check that the numbers match up



Given some beaming angle, θ, and some efficiency η, how many do we
expect to see in some given time t, given that there are n CBC events.

1. Set "observed GRBs" to zero
2. Draw n values of i from a uniform distribution, cos(i) ~ U(0,1)
3. If i < θ we would observe the GRB, and so we increment "observed GRBs"
4. Repeat this for a range of values of n

* Results
** O1 Jet angle posterior
   | Lower | MAP	 | Median	 | Upper |
   |-------+-------------+----------------+-------|
   |  1.48 |        2.47 |           4.33 | 30.96 |
   |  1.41 |        2.44 |           4.53 | 46.88 |
   |  1.17 |        0.68 |           2.70 | 13.89 |
   |  1.65 |        2.63 |           3.81 | 19.53 |

** O2 Jet angle posterior
   | Lower |  MAP | Median | Upper |
   |-------+------+--------+-------|
   |  1.29 | 0.67 |   2.96 | 15.22 |
   |  1.23 | 0.66 |   3.06 | 34.06 |
   |  1.05 | 0.65 |   1.90 |  5.04 |
   |  1.48 | 2.52 |   2.70 |  7.14 |


* Post GW170817 fall-out

** Conversation with Siong on Tuesday 3 October
  ➡<15:03:55> "Ik Siong Heng": I was looking at the GRB-GW paper and thinking about that
  ➡<15:04:06> "Daniel Williams [h]": Yeah
  ➡<15:04:25> "Daniel Williams [h]": I'm not sure what effect the top-hat-or-not situation has
  ➡<15:07:14> "Ik Siong Heng": For us, it does because the approach assumes an "on-off" counting
  ➡<15:09:25> "Daniel Williams [h]": Sure
  ➡<15:09:29> "Daniel Williams [h]": That's a good point
  ➡<15:10:45> "Ik Siong Heng": Perhaps the easiest thing to do in the near term is to assume an updated, localised rate based on the detection of GW170817A
  ➡<15:11:06> "Ik Siong Heng": we can convert GW detection volume into redshift
  ➡<15:11:25> "Ik Siong Heng": and then find and appropriate corresponding rate
  ➡<15:11:50> "Ik Siong Heng": and then, we redo the calculation based on that local rate
  ➡<15:12:49> "Ik Siong Heng": Perhaps this is something we should thought of earlier because I think it makes sense to have a GRB beaming limit based on a localised detection volume
  ➡<15:12:54> "Ik Siong Heng": ....maybe
  ➡<15:13:03> "Daniel Williams [h]": Hmm, okay
  ➡<15:13:20> "Ik Siong Heng": Chris may have a little more time now and you could find him to have a chat about this

** A local rate?
   It's clear that things are more complicated than we had originally
   hoped, and that we have two different scenarios to consider.  The
   first of these is that the rate which we were using in the first
   place is probably wrong; the second is that it's now not clear that
   all sGRB observations are of the beamed emission (although
   GRB170817A is probably the only example of an observation where it
   seems likely that the emission is not from the beaming cone). 

   I'm not sure that there's a simple and neat way around the second
   problem; we may want to assume a model (e.g. the strongly beamed
   model from the left hand cartoon in figure 4 of the GRB association
   paper) and work off that, since the paper doesn't provide strong
   evidence for which model we should use, and assuming a structured
   jet substantially complicates matters.

   For the first problem Siong's suggestion seems sensible, which is
   that we should limit the inspiral distance for the detector into a
   redshift, then we can calculate the rate of GRBs which are expected
   to occur within that region of space. This introduces a new prior
   (on H0) into the analysis.


* Redraft of the paper

** Observing scenarios table

   | Epoch       | observing time | horizon distance |       search volume | $N$ |
   |             |           [yr] |            [Mpc] | [\ee{6} Mpc³yr^{-1} |     |
   |-------------+----------------+------------------+---------------------+-----|
   | 2015 - 2016 |                |                  |                     |     |
   | 2016 - 2017 |            0.5 |              100 |                 1.3 |   1 |
   | 2017 - 2018 |           0.75 |              145 |                 6.5 |   3 |
   | 2019 +      |              1 |              200 |                  20 |  10 |
   | 2022 +      |              1 |              200 |                  40 |  20 |

